main: com.xironite.buildedit.Main
name: BuildEdit
author: Wassabi
version: 1.0
description: "Custom worldedit for survival servers."
api-version: 1.21

softdepend:
  - packetevents
  - WorldGuard

commands:
  buildedit:
    description: Main command for BuildEdit
    usage: /buildedit [subcommand]
    aliases: [ be, bedit ]
    permission: buildedit.use
    permission-message: You do not have permission to use this command.
  set:
    description: Set selected area with the specified blocks
    usage: /set [blocks] [flags]
    permission: buildedit.edit.set
    permission-message: You do not have permission to use this command.
  walls:
    description: Set selected are with walls
    usage: /walls [blocks] [flags]
    permission: buildedit.edit.walls
    permission-message: You do not have permission to use this command.